# Generated by Django 3.0.7 on 2020-06-28 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drinkName', models.CharField(max_length=256)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('username', models.CharField(max_length=256)),
                ('userUf', models.CharField(max_length=256)),
                ('userCity', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('placeUf', models.CharField(max_length=256)),
                ('placeCity', models.CharField(max_length=256)),
                ('availableDrinks', models.ManyToManyField(to='api.Drink')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('createdAt', models.DateField(auto_now=True)),
                ('users', models.ManyToManyField(to='api.User')),
            ],
        ),
        migrations.AddField(
            model_name='drink',
            name='foundPlace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Place'),
        ),
    ]
