# Generated by Django 3.0.7 on 2020-07-02 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drinkName', models.CharField(max_length=256)),
                ('realQuantity', models.IntegerField(default=0)),
                ('digitalQuantity', models.IntegerField(default=0)),
                ('imageUrl', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('placeUf', models.CharField(max_length=256)),
                ('placeCity', models.CharField(max_length=256)),
                ('contact', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=512)),
                ('hasMusic', models.BooleanField(default=False)),
                ('hasKidSpace', models.BooleanField(default=False)),
                ('hasWifi', models.BooleanField(default=False)),
                ('hasAccessibility', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('username', models.CharField(max_length=256)),
                ('userUf', models.CharField(max_length=256)),
                ('userCity', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=1024)),
                ('userImage', models.CharField(max_length=1024)),
                ('accountBalance', models.FloatField(default=0)),
                ('ambevPoints', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('token', models.CharField(default='AUTO', max_length=128)),
                ('finished', models.BooleanField(default=False)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Drink')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('createdAt', models.DateField(auto_now=True)),
                ('users', models.ManyToManyField(to='api.User')),
            ],
        ),
        migrations.AddField(
            model_name='drink',
            name='foundPlace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Place'),
        ),
    ]
